Name: WEIWEN WU
Place of Birth: China
Address: Sun Yat-Sen University in Shenzhen campus
Email: weiwenwu12@gmail.com and wuweiw7@mail.sysu.edu.cn
Personal website: https://www.researchgate.net/profile/Weiwen-Wu
Phone: +86 15730333674
 

EDUCATION
09/2014-06/2019, Chongqing University, Prof. Fenglin Liu
09/2017-09/2018, University of Massachusetts Lowell, Prof. Hengyong Yu
09/2010-06/2014, Nanchang Hangkong University,  	   Bachelor 


EXPERIENCE
06/2019-12/2020,	University of Hong Kong, 	Varut Vardhanabhuti,	Postdoctor 
12/2020-12/2021,	Renss. Polyte. Insti.,	Ge Wang (Inventor Fellow), 	Postdoctor
12/2021-Now,	    Sun Yat-Sen University,	Associate Professor
PUBLICATIONS
Journal Papers: (# indicates the contribution of authors are equal, # indicates correspond author)

2021
[34].Weiwen Wu, Lieza Vanden Broeke, Fenglin Liu, Varut Vardhanabhuti* and Ge Wang. “Deep Learning based spectral CT Imaging [J]”. Neural Networks , 2021.
[33]. Shaoyu Wang, Haijun Yu, Yarui Xi, Changcheng Gong, Weiwen Wu*, and Fenglin Liu*. “Spectral-Image Decomposition coupling with Energy-fusion Sensing for Spectral CT Reconstruction”. IEEE Transactions on Instrument and Measurement, 2021. DOI: 10.1109/TIM.2021.307855.
[32].Weiwen Wu, Dianlin Hu, Chuang Niu, Hengyong Yu*, Varut Vardhanabhuti* and Ge Wang*. “DRONE: Dual-domain Residual-based Optimization NEtwork for Sparse-view CT Reconstruction”. IEEE Transactions on Medical Imaging, 2021. DOI: 10.1109/TMI.2021.3078067. 
[31].Broeke, L.V., Grillon, M., Yeung, A.W.K., Wu, W., Tanaka, R. and Vardhanabhuti, V., 2021. “Feasibility of photon-counting spectral CT in dental applications—a comparative qualitative analysis”. BDJ open, 7(1), pp.1-8.
[30].Weiwen Wu, Dianlin Hu, Kang An, Shaoyu Wang and Fulin Luo*. “A high-quality photon-counting CT technique based on weight adaptive total-variation and image-spectral tensor factorization for small animals imaging [J]”. IEEE Transactions on Instrument and Measurement, 2021. 70: 2502114.
[29].Weiwen Wu, Jun Shi, Hengyong Yu, Weifei Wu* and Varut Vardhanabhuti*. “Tensor Gradient L0-norm Minimization based Low-dose CT Imaging and Its Application to COVID-19”. IEEE Transactions on Instrument and Measurement, 2021, 70 (4503012)

2020
[28].Ramandeep Singh, Weiwen Wu, Ge Wang, Mannudeep K. Kalra. Artificial Intelligence in Image Reconstruction: The Change is Here. Physica Medica, 79: 113-125, 2020. 
[27]. Haijun Yu, Shaoyu Wang, Weiwen Wu*, Changcheng Gong, Zhenzhen Pi and Fenglin Liu*. “Weighted Adaptive Non-local Dictionary Reconstruction for Low-dose CT [J]”. Signal Processing, 107871, 2020. 
[26]. Qian Wang, Weiwen Wu, Shiwo Deng, Yining Zhu, and Hengyong Yu*. “Locally linear transform based three-dimensional gradient L_0-norm minimization for spectral CT reconstruction”. Medical Physics, 47(10): 4810-4826, 2020. 
[25].Kang An, Jue Wang, Rifeng Zhou, Fenglin Liu, Weiwen Wu*. “Ring-artifacts removal  for photon-counting CT [J]”. Optics Express, 2020, 28(17), 25180-25193. 
[24]. Haichen Zhu, Dan Tong, Lu Zhang, Shijie Wang, Weiwen Wu, Hui Tang, Yang Chen*, Limin Luo, Jian Zhu, Baosheng Li. “Temporally downsampled cerebral CT perfusion image restoration using deep residual learning [J]”. International Journal of Computer Assisted Radiology and Surgery, 2020, 15(2), 193-201. (中科院SCI 3区, IF=2.155)
[23]. Weiwen Wu, Haijun Yu, Peijun Chen, Fulin Luo, Fenglin Liu*, Qian Wang, Yining Zhu, Yanbo Zhang, Jian Feng and Hengyong Yu*. “Dictionary learning based Image-domain Material Decomposition for spectral CT [J]”. Physics in Medicine & Biology, 2020. 
[22]. Weiwen Wu, Peijun Chen, Fenglin Liu* and Hengyong Yu*. “Generalized Dictionary learning based Image-domain Material Decomposition for spectral CT [J]”. IEEE Transactions on Radiation and Plasma Medical Sciences, 2020. DOI: 10.1109/TRPMS.2020.2997880. 
[21]. Moran Xu, Dianlin Hu, Fenglin Liu, Fulin Luo, Weiwen Wu*. “Limited angle X ray CT Reconstruction using Image Gradient ℓ0 norm with Dictionary Learning”. IEEE Transactions on Radiation and Plasma Medical Sciences, 2020. DOI: 10.1109/TRPMS.2020.2991887.
[20]. Shaoyu Wang, Weiwen Wu, Jian Feng, Fenglin Liu, Hengyong Yu. “Low-dose Spectral CT Reconstruction Based on Image-gradient L0-norm and Adaptive Spectral PICCS”. Physics in Medicine & Biology, 2020. 

2019
[19]. Weiwen Wu, Fenglin Liu*, Yanbo Zhang, Qian Wang, Hengyong Yu*. “Non-local low-rank cube-based tensor factorization for Spectral CT reconstruction [J]”. IEEE Transactions on Medical Imaging, 2019, 38(4): 1079-1093.
[18]. Weiwen Wu, Qian Wang, Fenglin Liu, Yining Zhu and Hengyong Yu*. “Block Matching Frame based Material Reconstruction for Spectral CT [J]”. Physics in Medicine & Biology, 2019, 64(23): 235011.
[17]. Weiwen Wu, Peijun Chen, Vince Varut Vardhanabhuti, Weifei Wu* and Hengyong Yu*. “Improved Material Decomposition with a Two-step Regularization for spectral CT [J]”. IEEE Access, 2019.
[16]. Haijun Yu #, Weiwen Wu #, Hengyong Yu, Changcheng Gong, Junru Jiang and Fenglin Liu*. “Image Gradient L0-norm based PICCS (L0- PICCS) for Swinging Multi-source CT Reconstruction[J]”. Optics Express, 2019, 25(20): 24215-24235. 
[15]. Wenjun Xia, Weiwen Wu, Fenglin Liu, Hengyong Yu, Ge Wang and Yi Zhang*. “Spectral CT Reconstruction – ASSIST: Aided by Self-Similarity in Image-Spectral Tensors [J]”. IEEE Transaction on Computational Imaging, 2019, 5(3): 420-436. 
[14]. Dianlin Hu, Weiwen Wu, Jin Liu, Limin Luo and Yang Chen*. “SISTER: Spectral-Image Similarity-based Tensor with Enhanced-sparsity Reconstruction for Sparse-view Multi-energy CT [J]”. IEEE Transaction on Computational Imaging, 2020, 6, pp. 477-490. 
[13]. Yufeng Gao,Yu Song, Xiangrui Yin, Weiwen Wu, Lu Zhang, Yang Chen* and Wanyin Shi. “Deep learning-based digital subtraction angiography image generation [J]”. International Journal of Computer Assisted Radiology and Surgery, 2019, 14(10): 1775–1784. 
[12]. Jin Liu, Yi Zhang, Qianlong Zhao, Tianling Lv and Weiwen Wu, Ning Cai, Guotao Quan, Wei Yang, Yang Chen, Limin Luo, Huazhong Shu and Jean Coatrieux. “Deep Iterative Reconstruction Estimation (DIRE): Approximate Iterative Reconstruction Estimation for Low-dose CT Imaging”. Physics in Medicine & Biology, 2019, 64(13): 135007. (中科院SCI 2区，IF=3.03)
 
2018
[11]. Weiwen Wu, Yanbo Zhang, Qian Wang, Fenglin Liu*, Peijun Chen and Hengyong Yu. “Low-dose spectral CT reconstruction using L0 image gradient and tensor dictionary [J]”. Applied Mathematical Modelling, 2018, 63: 538-557.
[10]. Weiwen Wu, Yanbo Zhang, Qian Wang, Fenglin Liu*, Fulin Luo and Hengyong Yu*. “Spatial-Spectral Cube Matching Frame for Spectral CT Reconstruction [J]”. Inverse Problems, 2018, 34 (10): 104003.
[9]. Weiwen Wu, Hengyong Yu*, Wenxiang Cong and Fenglin Liu*. “Theoretically exact backprojection filtration algorithm for multi-segment linear trajectory [J].” Physics in Medicine & Biology, 2018, 63(1): 015037.
[8]. Fulin Luo, Chengwei Li, Weiping Tu and Weiwen Wu. “Adaptive Weighted Total Variation Minimization based Alternating Direction Method of Multipliers for Limited Angle CT Reconstruction [J]”. IEEE Access, 2018, 6: 64225-64236. 
[7]. Shaoyu Wang, Weiwen Wu, Changcheng Gong and Fenglin Liu*. “Study of Parallel Translation Computed Laminography Imaging”. Acta Optica Sinica, 2018, 38(12):1211002.
[6]. Peijun Chen, Peng Feng*, Weiwen Wu, Xiaochuan Wu, Xiang Fu, Biao Wei and Peng He*. “Material Discrimination by Multi-Spectral CT Based on Image Total Variation and Tensor Dictionary [J]”. Acta Optica Sinica, 2018, 38(11):1111002. 
[5]. Xuyang Feng, Weiwen Wu, Huijie Zhu, Haijun Yu and Fenglin Liu*. “Monte Carlo Simulation for a Dynamic Bowtie Filter with Cone-beam CT[J]”. CT Theory and Application Research, 2018, 27(3): 316. 

2017 and Before
[4]. Weiwen Wu, Hengyong Yu, Changcheng Gong and Fenglin Liu*. “Swinging multi-source industrial CT systems for aperiodic dynamic imaging [J]. Optics Express, 2017, 25(20): 24215-24235.
[3]. Weiwen Wu, Hengyong Yu*, Shaoyu Wang and Fenglin Liu*. “BPF-type region-of-interest reconstruction for parallel translational computed tomography [J]”. Journal of X-ray Science and Technology, 2017, 25(3): 487-504.
[2]. Weiwen Wu, Chao Quan and Fenglin Liu*. “Filtered Back-Projection Image Reconstruction Algorithm for Opposite Parallel Linear CT Scanning [J]”. Acta Optica Sinica, 2016, 36 (9), 0911009.
[1]. Fenglin Liu*, Chao Quan, Weiwen Wu, Peng Feng and Yufang Cai. “Synchronous scanning mode of industrial computed tomography for multiple objects test [J]”. Journal of X-ray Science and Technology, 2017, 25(5): 765-775.

Conference Papers: (# indicate the contribution of authors are equal)
[1]. Weiwen Wu, Yanbo Zhang, Qian Wang, Fenglin Liu, Peijun Chen and Hengyong Yu. "Sparse-view Spectral CT Reconstruction Using Image Gradient L0–norm and Tensor Dictionary [C]," The Fifth International Conference on Image Formation in X-Ray Computed Tomography, 2018, Salt Lake, U.S.A, pp. 344-347. (poster)
[2]. Weiwen Wu, Gang Chen and Fenglin Liu. “Backprojection Filtering Image Reconstruction for Linear Scan Based Tomography.” The First International Conference on Sensing and Imaging, 2016, Taiyuan, China. (Presentation)
[3]. Huijie Zhu, Fuqiang Gao, Weiwen Wu, Fenglin Liu, " Dynamic bowtie filter design with Monte Carlo simulation for cone-beam CT [C]," Control And Decision Conference (CCDC), 2017 29th. IEEE, 2017: 3160-3165. 
[4]. Qian Wang, Weiwen Wu and Hengyong Yu. "Locally Linear Transform based Gradient L0-norm minimization for spectral CT reconstruction [C]," The Fifth International Conference on Image Formation in X-Ray Computed Tomography. 2018, Salt Lake, U.S.A, pp. 364-368.
[5]. Wenjun Xia, Weiwen Wu, Fenglin Liu, Hengyong Yu, Ge Wang, Yi Zhang. “SPECTRAL CT RECONSTRUCTION VIA SELF-SIMILARITY IN IMAGESPECTRAL TENSORS [C]”. The Engineering in Medicine and Biology, 2018. (Published)

HONORS AND AWARDS
●09/2014	Chongqing University “Excellent fresh graduate” award
●09/2016	Award for Excellent Papers in Journal of Optics
●06/2017	Chinese Government Scholarship

PROFESSIONAL MEMBERSHIPS
Guest Editor for “EURASIP Journal on Advances in Signal Processing” (SCI index)
JOURNAL REVIEWER
●IEEE Transactions on Medical Imaging
●IEEE Transactions on Artificial Intelligence 
●IEEE Journal of Biomedical and Health Informatics
●Medical Physics
●Physics in Medicine and Biology
●Journal of X-ray science and technology
●IEEE Access
●Optics and Lasers in Engineering
●Journal of inverse and ill-posed problems
●Physical Science Journal
●Informatics in Medicine Unlocked
●Computerized Medical Imaging and Graphics
●Philosophical Transactions of the Royal Society A
